version: "3.8"

services:
  web:
    build:
      context: ./web

    command: gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind ${HOST}:${PORT} --access-logfile -
    volumes:
      - ./web:/app
    ports:
      - 8000:${PORT}
    restart: 'always'
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres

  pyrogram_client:
    build:
      context: ./pyrogram_client
    command: python3 main.py
    volumes:
      - ./pyrogram_client:/app
    restart: 'always'
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres


  postgres:
    image: postgres:16-alpine3.18
    restart: 'always'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.0.4
    restart: 'always'
    volumes:
      - ./data/cache:/data